name: BuildAndPush
on:
  push:
    branches: [main]

jobs:
  build-and-push-docker-image:
    name:  BuildAndPush
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.version.outputs.date }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env for django app
        run: |
          cat <<-EOF > .env 
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_NAME=${{ secrets.DB_NAME}}
          DB_PASS=${{ secrets.DB_PASS }}
          CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}
          REDIS_URL=${{ secrets.REDIS_URL }}
          EOF

      - name: Get current date
        id: version
        run: echo "date=$(date +'%Y-%m-%d-%s')" >> $GITHUB_OUTPUT 

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Echo Docker image tag
        run: echo "date=$(date +'%Y-%m-%d-%s')" >> $GITHUB_ENV
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: brotherfranklyn/category-two:${{ steps.version.outputs.date }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref:  brotherfranklyn/category-two:${{ steps.version.outputs.date }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: '*'
          severity: 'CRITICAL,HIGH'
